### ISSUE TITLE
Android版でgetDuration()がエラー

### ISSUE THREAD

**Issue by wakame-tech** [worldrize/wr-app#314]
```
E/flutter ( 8382): [ERROR:flutter/lib/ui/ui_dart_state.cc(166)] Unhandled Exception: PlatformException(Unexpected error!, Attempt to invoke virtual method 'int android.media.MediaPlayer.getDuration()' on a null object reference, java.lang.NullPointerException: Attempt to invoke virtual method 'int android.media.MediaPlayer.getDuration()' on a null object reference
E/flutter ( 8382):      at xyz.luan.audioplayers.WrappedMediaPlayer.getDuration(WrappedMediaPlayer.java:148)
E/flutter ( 8382):      at xyz.luan.audioplayers.AudioplayersPlugin.handleMethodCall(AudioplayersPlugin.java:110)
E/flutter ( 8382):      at xyz.luan.audioplayers.AudioplayersPlugin.onMethodCall(AudioplayersPlugin.java:44)
E/flutter ( 8382):      at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
E/flutter ( 8382):      at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
E/flutter ( 8382):      at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:692)
E/flutter ( 8382):      at android.os.MessageQueue.nativePollOnce(Native Method)
E/flutter ( 8382):      at android.os.MessageQueue.next(MessageQueue.java:336)
E/flutter ( 8382):      at android.os.Looper.loop(Looper.java:174)
E/flutter ( 8382):      at android.app.ActivityThread.main(ActivityThread.java:7356)
E/flutter ( 8382):      at java.lang.reflect.Method.invoke(Native Method)
E/flutter ( 8382):      at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
E/flutter ( 8382):      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
E/flutter ( 8382): )
E/flutter ( 8382): #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:572:7)
E/flutter ( 8382): #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:161:18)
E/flutter ( 8382): <asynchronous suspension>
E/flutter ( 8382): #2      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:334:12)
E/flutter ( 8382): #3      AudioPlayer._invokeMethod (package:audioplayers/audioplayers.dart:319:10)
E/flutter ( 8382): #4      AudioPlayer.getDuration (package:audioplayers/audioplayers.dart:528:12)
E/flutter ( 8382): #5      VoicePlayer.playMessages.<anonymous closure> (package:wr_app/presentation/voice_player.dart:91:43)
E/flutter ( 8382): <asynchronous suspension>
E/flutter ( 8382): #6      VoicePlayer.playMessages.<anonymous closure> (package:wr_app/presentation/voice_player.dart)
E/flutter ( 8382): #7      Future.forEach.<anonymous closure> (dart:async/future.dart:508:26)
E/flutter ( 8382): #8      Future.doWhile.<anonymous closure> (dart:async/future.dart:550:26)
E/flutter ( 8382): #9      _rootRunUnary (dart:async/zone.dart:1198:47)
E/flutter ( 8382): #10     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 8382): #11     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 8382): #12     _CustomZone.bindUnaryCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1042:26)
E/flutter ( 8382): #13     Future.doWhile (dart:async/future.dart:566:18)
E/flutter ( 8382): #14     Future.forEach (dart:async/future.dart:506:12)
E/flutter ( 8382): #15     VoicePlayer.playMessages (package:wr_app/presentation/voice_player.dart:87:18)
E/flutter ( 8382): #16     PhraseExampleCard.build.<anonymous closure>.<anonymous closure> (package:wr_app/presentation/lesson/pages/section_page/widgets/phrase_example_card.dart:231:33)
E/flutter ( 8382): #17     GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:184:24)
E/flutter ( 8382): #18     TapGestureRecognizer.handleTapUp (package:flutter/src/gestures/tap.dart:524:11)
E/flutter ( 8382): #19     BaseTapGestureRecognizer._checkUp (package:flutter/src/gestures/tap.dart:284:5)
E/flutter ( 8382): #20     BaseTapGestureRecognizer.acceptGesture (package:flutter/src/gestures/tap.dart:256:7)
E/flutter ( 8382): #21     GestureArenaManager.sweep (package:flutter/src/gestures/arena.dart:158:27)
E/flutter ( 8382): #22     GestureBinding.handleEvent (package:flutter/src/gestures/binding.dart:224:20)
E/flutter ( 8382): #23     GestureBinding.dispatchEvent (package:flutter/src/gestures/binding.dart:200:22)
E/flutter ( 8382): #24     GestureBinding._handlePointerEvent (package:flutter/src/gestures/binding.dart:158:7)
E/flutter ( 8382): #25     GestureBinding._flushPointerEventQueue (package:flutter/src/gestures/binding.dart:104:7)
E/flutter ( 8382): #26     GestureBinding._handlePointerDataPacket (package:flutter/src/gestures/binding.dart:88:7)
E/flutter ( 8382): #27     _rootRunUnary (dart:async/zone.dart:1206:13)
E/flutter ( 8382): #28     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
E/flutter ( 8382): #29     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1005:7)
E/flutter ( 8382): #30     _invoke1 (dart:ui/hooks.dart:267:10)
E/flutter ( 8382): #31     _dispatchPointerDataPacket (dart:ui/hooks.dart:176:5)
E/flutter ( 8382): 
```

**Comment by wakame-tech** [comment]
`Completor` で実装してたので問題なし
