### ISSUE TITLE
androidが機能してない　LINEで報告の通り

### ISSUE THREAD

**Issue by world-rize** [worldrize/wr-app#414]
# ❓ 概要

# 📚 参考

**Comment by wakame-tech** [comment]
実機ログ
```
2020-11-04 02:48:09.484 5586-5626/? I/flutter: [02:48:09][INFO] ⚙ Env
2020-11-04 02:48:09.485 5586-5626/? I/flutter: [02:48:09][INFO] ⚙ Flavor Flavor.production
2020-11-04 02:48:09.485 5586-5626/? I/flutter: [02:48:09][INFO] 🔥 FirebaseAnalytics Initialized
2020-11-04 02:48:09.485 5586-5626/? I/flutter: [02:48:09][INFO] 🔥 FirebaseAnalyticsObserver Initialized
2020-11-04 02:48:09.488 859-859/? D/android.hardware.power@1.3-service.pixel-libperfmgr: LAUNCH: 0
2020-11-04 02:48:09.488 5586-5626/? I/flutter: [02:48:09][INFO] 📄 Load pubspec.yml
2020-11-04 02:48:09.491 5586-5626/? I/flutter: [02:48:09][INFO] 🔥 SharedPreferences Initialized
2020-11-04 02:48:09.492 5586-5626/? I/flutter: [02:48:09][INFO] 🔥 Contentful Initialized
2020-11-04 02:48:09.492 5586-5626/? I/flutter: [02:48:09][INFO] 🔥 Admob Initialized
2020-11-04 02:48:09.499 5586-5586/? D/DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraMobileAdsSettingManagerCreatorImpl
2020-11-04 02:48:09.543 2410-713/? W/NetworkScheduler: Error inserting flex_time=3181000 job_id=-1 period=6363000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=203915000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1604425689533 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0, error message: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE) [CONTEXT service_id=218 ]
2020-11-04 02:48:09.550 1372-7253/? D/ConnectivityService: requestNetwork for uid/pid:10242/5586 NetworkRequest [ TRACK_DEFAULT id=958, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242] ]
2020-11-04 02:48:09.551 1372-1748/? D/WifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=958, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242] ] with score 60 and serial -1
2020-11-04 02:48:09.551 1372-1748/? D/UntrustedWifiNetworkFactory: got request NetworkRequest [ TRACK_DEFAULT id=958, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242] ] with score 60 and serial -1
2020-11-04 02:48:09.551 1372-1780/? D/Ethernet: got request NetworkRequest [ TRACK_DEFAULT id=958, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242] ] with score 60 and serial -1
2020-11-04 02:48:09.551 1372-1779/? D/WIFI_AWARE_FACTORY: got request NetworkRequest [ TRACK_DEFAULT id=958, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242] ] with score 60 and serial -1
2020-11-04 02:48:09.552 2140-2140/? D/PhoneSwitcherNetworkRequstListener: got request NetworkRequest [ TRACK_DEFAULT id=958, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Uid: 10242] ] with score 60 and serial -1
2020-11-04 02:48:09.561 2410-713/? W/NetworkScheduler: Error inserting flex_time=3181000 job_id=-1 period=6363000 source=16 requires_charging=0 preferred_network_type=1 target_class=com.google.android.gms.measurement.PackageMeasurementTaskService user_id=0 target_package=com.google.android.gms tag=Measurement.PackageMeasurementTaskService.UPLOAD_TASK_TAG task_type=0 required_idleness_state=0 service_kind=0 source_version=203915000 persistence_level=1 preferred_charging_state=1 required_network_type=0 runtime=1604425689558 retry_strategy={"maximum_backoff_seconds":{"3600":0},"initial_backoff_seconds":{"30":0},"retry_policy":{"0":0}} last_runtime=0, error message: UNIQUE constraint failed: pending_ops.tag, pending_ops.target_class, pending_ops.target_package, pending_ops.user_id (code 2067 SQLITE_CONSTRAINT_UNIQUE) [CONTEXT service_id=218 ]
2020-11-04 02:48:09.596 5586-5682/? W/cr_media: Requires BLUETOOTH permission
2020-11-04 02:48:09.607 5654-5690/? I/cr_LibraryLoader: Loaded native library version number "86.0.4240.185"
2020-11-04 02:48:09.607 5586-5626/? I/flutter: [02:48:09][INFO] 🔥 notificator Initialized
2020-11-04 02:48:09.608 5586-5626/? I/flutter: [02:48:09][INFO] 🔥 sign in with apple Initialized
2020-11-04 02:48:09.608 5654-5690/? I/cr_CachingUmaRecorder: Flushed 1 samples from 1 histograms.
2020-11-04 02:48:09.614 5586-5626/? E/flutter: [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: NoSuchMethodError: The getter 'length' was called on null.
    Receiver: null
    Tried calling: length
    #0      Uri.parse (dart:core/uri.dart:792)
    #1      Dsn.parse (package:sentry/src/base.dart:1172)
    #2      new SentryClient.base (package:sentry/src/base.dart:112)
    #3      new SentryIOClient._ (package:sentry/src/io.dart:77)
    #4      new SentryIOClient (package:sentry/src/io.dart:57)
    #5      createSentryClient (package:sentry/src/io.dart:122)
    #6      new SentryClient (package:sentry/src/base.dart:37)
    #7      setupGlobalSingletons (package:wr_app/run_app_with_flavor.dart:113)
    <asynchronous suspension>
    #8      runAppWithFlavor (package:wr_app/run_app_with_flavor.dart:126)
    <asynchronous suspension>
```

**Comment by wakame-tech** [comment]
.env がなかっただけ
